core/urls.py
from django.urls import path
from .views import HomePageView, DoctorPageView, BookAppointment, AppointmentDetailView

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('doctors/', DoctorPageView.as_view(), name='doctor-page'),
    path('book-appointment/', BookAppointment.as_view(), name='book-appointment'),
    path('<slug:slug>/', AppointmentDetailView.as_view(),
         name='appointment_detail'),
]

docline247/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# endif

core/models.py
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.exceptions import ValidationError
from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    class Meta:
        db_table = 'dl_users'


class CategoryManager(models.Manager):

    def get_by_natural_key(self, name):
        return self.get(name=name)


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    icon = models.ImageField(upload_to='categories/')

    objects = CategoryManager()

    class Meta:
        db_table = 'dl_categories'

    def __str__(self) -> str:
        return self.name


class DoctorManager(models.Manager):

    def get_by_natural_key(self, name):
        return self.get(name=name)


class Doctor(models.Model):

    class Gender(models.TextChoices):
        M = 'M'
        F = 'F'
        T = 'T'

    YEAR_CHOICES = []
    for year in range(1980, datetime.now().year+1):
        YEAR_CHOICES.append((year, year))

    name = models.CharField(max_length=128, unique=True)
    gender = models.CharField(max_length=1, choices=Gender.choices)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField()
    year_of_employment = models.IntegerField(choices=YEAR_CHOICES)
    profile_pic = models.ImageField(upload_to='doctors/')

    objects = DoctorManager()

    class Meta:
        db_table = 'dl_doctors'

    def __str__(self) -> str:
        return self.name


class PatientManager(models.Manager):

    def get_by_natural_key(self, name):
        return self.get(name=name)


class Patient(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()
    dob = models.DateField()

    objects = PatientManager()

    class Meta:
        db_table = 'dl_patients'

    def __str__(self) -> str:
        return self.name


class Appointment(models.Model):

    class StatusChoices(models.TextChoices):
        IN_PROGRESS = 'IN PROGRESS', _('In Progress')
        ACCEPTED = 'ACCEPTED', _('Accepted')
        REJECTED = 'REJECTED', _('Rejected')
        CANCELED = 'CANCELED', _('Canceled')

    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date_of_appointment = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    time_slot = models.TimeField()
    message = models.TextField()
    slug = models.SlugField(max_length=250, null=True, blank=True)
    status = models.CharField(max_length=11,
                              choices=StatusChoices.choices, default=StatusChoices.IN_PROGRESS)

    class Meta:
        db_table = 'dl_appointments'

    def save(self, *args, **kwargs):
        if(self.doctor.category != self.category):
            raise ValidationError("Doctor and Category do not match")
        super(Appointment, self).save(*args, **kwargs)
        # endif

    def __str__(self) -> str:
        return str(self.patient)


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(pre_save_receiver, sender=Appointment)

core/forms.py
from django import forms
from datetime import datetime, date
from .models import Doctor, Category
from django.core.validators import MinLengthValidator
from .validators import past_date_validator, future_date_validator, name_validator


class AppointmentCreateForm(forms.Form):

    time_choices = (
        ('09:00:00', '09:00 AM'),
        ('10:30:00', '10:30 AM'),
        ('12:00:00', '12:00 PM'),
        ('16:00:00', '04:00 PM'),
        ('18:00:00', '06:00 PM'),
    )

    name = forms.CharField(max_length=128,
                           validators=[MinLengthValidator(3), name_validator],
                           widget=forms.TextInput(attrs={
                               'class': 'm-form__input m-form__input--name',
                               'placeholder': 'Name'
                           }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'm-form__input m-form__input--email',
        'placeholder': 'Email'
    }))

    dob = forms.DateField(validators=[past_date_validator],
                          widget=forms.DateInput(attrs={
                              'class': 'm-form__input m-form__input--dob',
                              'placeholder': 'Date of birth',
                              'type': 'date'
                          }))

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={
            'class': 'm-form__input m-form__input--designation',
        }))

    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(),
                                    widget=forms.Select(attrs={
                                        'class': 'm-form__input m-form__input--doctor',
                                    }))

    date_of_appointment = forms.DateField(validators=[future_date_validator],
                                          widget=forms.DateInput(attrs={
                                              'class': 'm-form__input m-form__input--doa',
                                              'placeholder': 'Date of appointment',
                                              'type': 'date'
                                          }))

    time_slot = forms.ChoiceField(choices=time_choices,
                                  widget=forms.Select(attrs={
                                      'class': 'm-form__input m-form__input--time',
                                  }))

    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'm-form__input m-form__input--notes',
        'placeholder': 'Convey details to doctor'
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = ""
        self.fields['email'].label = ""
        self.fields['dob'].label = ""
        self.fields['category'].empty_label = "Select a category"
        self.fields['doctor'].empty_label = "Select a doctor"
        self.fields['date_of_appointment'].label = ""
        self.fields['category'].label = ""
        self.fields['doctor'].label = ""
        self.fields['time_slot'].label = ""
        self.fields['message'].label = ""

    def clean(self):
        cleaned_data = super().clean()
        date_of_appointment = cleaned_data.get('date_of_appointment')
        time_slot = cleaned_data.get('time_slot')

        if(date_of_appointment == date.today()):
            if(time_slot <= str(datetime.now().time())):
                raise forms.ValidationError("Please select future time-slot")
            # endif
        # endif

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, UpdateView
from .models import Category, Doctor, Patient, Appointment
from django.views.generic import FormView
from django.urls import reverse, reverse_lazy
from .forms import AppointmentCreateForm
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.html import strip_tags
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.contrib import messages


class HomePageView(TemplateView):

    template_name = "core/home.html"


class DoctorPageView(ListView):

    template_name = 'core/doctor.html'
    paginate_by = 2
    model = Doctor
    ordering = 'id'
    context_object_name = 'doctors'

    def get_queryset(self):
        queryset = self.model.objects.all()
        if(self.request.GET.get('category')):
            queryset = Doctor.objects.filter(
                category__name=self.request.GET.get('category'))
        # endif

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        get_copy = self.request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        context['parameters'] = parameters
        return context


class BookAppointment(FormView):
    template_name = 'core/book-appointment.html'
    form_class = AppointmentCreateForm
    success_url = reverse_lazy('core:book-appointment')

    def post(self, request, *args, **kwargs):
        appointment_form = AppointmentCreateForm(request.POST)
        context = super(BookAppointment, self).get_context_data(**kwargs)
        if appointment_form.is_valid():
            cd = appointment_form.cleaned_data
            patient, created = Patient.objects.get_or_create(
                name=cd['name'], email=cd['email'], dob=cd['dob'])
            appointment = Appointment(
                patient_id=patient.id,
                date_of_appointment=cd['date_of_appointment'],
                category=cd['category'],
                doctor=cd['doctor'],
                time_slot=cd['time_slot'],
                message=cd['message']
            )
            appointment.save()
            messages.success(self.request, 'Form submitted successfully')

            # current_site = get_current_site(request)
            # subject = 'Appointment'
            # from_email = settings.EMAIL_HOST_USER
            # to = cd['email']
            # slug = Appointment.objects.get(
            #     id=appointment.id).slug
            # message = render_to_string(
            #     'core/email.html', {
            #         'name': cd['name'],
            #         'date_of_appointment': cd['date_of_appointment'],
            #         'domain': current_site,
            #         'slug': slug,
            #     }
            # )
            # text_content = strip_tags(message)
            # msg = EmailMultiAlternatives(
            #     subject, text_content, from_email, [to])
            # msg.attach_alternative(message, "text/html")
            # msg.send()

            return self.form_valid(appointment_form)

        else:
            return render(self.request, 'core/book-appointment.html', context)


class AppointmentDetailView(UpdateView):
    template_name = 'core/appointment-detail.html'
    model = Appointment
    context_object_name = 'appointment'
    fields = ['status']

    def get_success_url(self):
        return reverse('core:appointment_detail', kwargs={'slug': self.object.slug})

core/templates/core/appointment-detail.html
{% extends 'master.html' %} {% load static %} {% block addl_stylesheets %}
<link rel="stylesheet" href="{% static 'css/dist/p-appointment-detail.css' %}" />

{% endblock addl_stylesheets %} {% block view_content %}
<header class=" m-header">
	<a href="/core" class="m-header__img">
		<img src="{% static 'images/home.svg' %}" alt="go-to-home">
	</a>

	<span class="m-header__heading h4">CHECK APPOINTMENT STATUS</span>
</header>
<main class="p-appointment-detail">
	<div class="m-actor">
		<p class="m-actor__name m-actor__name--patient">{{appointment.patient}}</p>
		<img src="{% static 'images/link.svg' %}" alt="link">
		<p class="m-actor__name m-actor__name--doctor">{{appointment.doctor}}</p>
	</div>
	
	<div class="m-grid-info">
		<div class="m-grid-info__item m-grid-info__item--doa">{{appointment.date_of_appointment}}</div>
		
		<div class="m-grid-info__item">{{appointment.time_slot}}</div>
		
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %} 
			{{form.as_p}}
			<button type="submit" class=" m-grid-info__item m-grid-info__item--cancel">Cancel Appointment</button> 
		</form>
	</div>
    
	<div>
		<p id="status" class="p-appointment-detail__status">{{appointment.status}}</p>
	</div>
</main>
<script>
	var labels = document.getElementsByTagName("LABEL");
	for (var i = 0; i < labels.length; i += 1) {
		labels[i].style.display = "none";
	}
	var cancel_input = document.getElementById("id_status");
	cancel_input.value = "CANCELED";
	cancel_input.style.display = "none";
</script>
{% endblock view_content %}
{% block addl_scripts %}
<script src="{% static 'js/appointment-detail.js' %}"></script>
{% endblock addl_scripts %}

core/templates/core/book-appointment.html
{% extends 'master.html' %}

{% load static %}

{% block addl_stylesheets %}
<link rel="stylesheet" href="{% static 'css/dist/p-book-appointment.css' %}">
{% endblock addl_stylesheets %}

{% block view_content %}

<main class="p-book-appointment">
    <header class="m-header">
        <a href="{% url 'core:home-page' %}" class="m-header__img">
            <img src="{% static 'images/home.svg' %}" alt="go-to-home">
        </a>

        <span class="m-header__heading h4">BOOK AN APPOINTMENT</span>
    </header>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div>
                    {{ message }} 
                    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    

    <form action="" class="m-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% for field in form %}
            {{ field }}
            <p class="m-form__error">{{ field.errors.as_text }}</p>
        {% endfor %}

        <p class="m-form__error m-form__error--timeslot">{{form.non_field_errors}}</p>

        <button class="m-btn m-btn--blue m-form__submit" type="submit">SUBMIT</button>
    </form>
</main>
{% endblock view_content %}
{% block addl_scripts %}
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/book-appointment.js' %}"></script>
{% endblock addl_scripts %}

core/templates/core/doctor.html
{% extends 'master.html' %}

{% load static %}

{% block addl_stylesheets %}
<link rel="stylesheet" href="{% static 'css/dist/p-doctor.css' %}">
{% endblock addl_stylesheets %}

{% block view_content %}
<main class="p-doctor">
    <header class="p-doctor__nav m-header">
        <a href="{% url 'core:home-page' %}" class="m-header__img">
            <img src="{% static 'images/home.svg' %}" alt="go-to-home">
        </a>

        <span class="m-header__heading h4">DOCTORS INFORMATION</span>
    </header>

    <div class="p-doctor__category m-category">
        {% for category in categories %}
        <a href="{% url 'core:doctor-page' %}?category={{category.name}}" class="m-category__item m-category-inner">
            <img src="{{category.icon.url}}" alt="{{category.name}}" class="m-category-inner__img">

            <span class="m-category-inner__name">{{category.name}}</span>
        </a>
        {% endfor %}

        <a href="{% url 'core:doctor-page' %}" class="m-category__item m-category-inner">
            <img src="{% static 'images/viewall.png'%}" alt="viewall" class="m-category-inner__img">

            <span class="m-category-inner__name">View all</span>
        </a>
    </div>

    {% for doctor in doctors %}
        {% include 'partials/_doctor-card.html' with object=doctor  %}
    {% endfor %}

    {% include 'partials/_pagination.html' %}
</main>
{% endblock view_content %}

core/templates/core/email.html
{% autoescape off %}
<h3>Hi <strong>{{ name }}</strong></h3>
<p>Date of Appointment: {{date_of_appointment}}</p>
<p> Here is a link:</p>
<a href="http://{{domain}}/core/{{slug}}">Check Status</a>
{% endautoescape %}

core/templates/core/home.html
{% extends 'master.html' %}

{% load static %}

{% block addl_stylesheets %}
<link rel="stylesheet" href="{% static 'css/dist/p-home.css' %}">
{% endblock addl_stylesheets %}

{% block view_content %}
<div class="p-home" id="p-home">
    <main class="p-home__main">
        <div id="sidenav" class="m-sidenav">
            <div class="m-sidenav__head m-navhead">
                <img src="{% static 'images/sidenav-icon.png' %}" alt="hospital-sign">
                <span class="m-navhead__heading">DOCLINE 24X7</span>
            </div>

            <hr class="m-sidenav__line">

            <nav class="m-sidenav__list m-nav">
                <a href="#myCarousel" class="m-nav__item m-nav__item--how">
                   How to book an <br> appointment?
                </a>

                <a href="" class="m-nav__item m-nav__item--book">
                    Book an appointment
                </a>

                <a href="#" class="m-nav__item m-nav__item--contact">
                    Contact Us
                </a>
                    
                <a href="#" class="m-nav__item m-nav__item--login">
                    Admin Login
                </a>
            </nav>

            <!-- <ul class="m-sidenav__list">
                <li>
                        <a href="#myCarousel" class="m-sidenav__items">
                            <span class="m-sidenav__item m-sidenav__item-how">How to book an <br> appointment?</span>
                        </a>
                </li>

                <li>
                    <a href="#" class="m-sidenav__items">
                        <span class="m-sidenav__item m-sidenav__item-book">Book an appointment</span>
                    </a>
                </li>

                <li>
                    <a href="#contact-us" class="m-sidenav__items">
                        <span class="m-sidenav__item m-sidenav__item-contact">Contact Us</span>
                    </a>
                </li>

                <li>
                    <a href="#" class="m-sidenav__items">
                        <span class="m-sidenav__item m-sidenav__item-login">Admin Login</span>
                    </a>
                </li>
            </ul> -->
        </div>
        
        <div class="m-main">
            <span onclick="openNav()" class="m-main__menuicon">
                <img src="{% static 'images/Hamburger menu.png' %}" alt="">
            </span>
    
            <div id="overlay" class="m-main__overlay" onclick="closeNav()"></div>
    
            <img src="{% static 'images/doctor-home.png' %}" class="m-main__hero" alt="">
    
            <h1 class="m-main__mainheading">DOCLINE 24x7</h1>    

            <div class="m-main__btns">
                <a href="{% url 'core:book-appointment' %}" class="m-btn m-btn--white">BOOK AN <br> APPOINMENT</a>
                <a href="{% url 'core:doctor-page' %}" class="m-btn m-btn--blue">DOCTOR DETAILS</a>
            </div>
        </div> 
    </main>

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active dot"></li>

            <li data-target="#myCarousel" data-slide-to="1" class="dot"></li>

            <li data-target="#myCarousel" data-slide-to="2" class="dot"></li>
        </ol>

        <div class="carousel-inner bg-white">
            <div class="m-card item active">
                <h1 class="m-card__head">GUIDELINES <br> STEP-1</h1>

                <div class="m-card__image">
                    <img src="{% static 'images/step-1.svg' %}" alt="">
                </div>

                <h3 class="m-card__sub-heading">VIEW DOCTOR DETAILS</h3>

                <p class="m-card__desc">
                    Refer the doctor details 
                    to choose the best 
                    based on your 
                    health needs. 
                </p>
            </div>

            <div class="m-card item">
                <h1 class="m-card__head">GUIDELINES <br> STEP-2</h1>

                <div class="m-card__image">
                    <img src="{% static 'images/step-2.svg' %}" alt="">
                </div>

                <h3 class="m-card__sub-heading">REQUEST APPOINMENT</h3>

                <p class="m-card__desc">
                    Fill the form by entering 
                    necessary details in the 
                    required fields and click 
                    submit button.
                </p>
            </div>

            <div class="m-card item">
                <h1 class="m-card__head">GUIDELINES <br> STEP-3</h1>

                <div class="m-card__image">
                    <img src="{% static 'images/step-3.svg' %}" alt="">
                </div>

                <h3 class="m-card__sub-heading">STATUS CHECKING</h3>

                <p class="m-card__desc">
                    Visit the link sent via the 
                    email to check your 
                    appointment status.
                </p>
            </div>
        </div>

        <a class="left carousel-control" href="#myCarousel"
            style="background: none; color: #237d9e; font-weight: bold; opacity: 100;" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="right carousel-control" href="#myCarousel"
            style="background: none; color: #237d9e; font-weight: bold; opacity: 100;" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="p-home__contact" id="contact-us">
        <div class="m-contact">
            <h3 class="m-contact__title">Contact Us</h3>

            <span class="m-contact-item m-contact-item--location">Lorem ipsum</span>
            <span class="m-contact-item m-contact-item--email">docline247@gmail.com</span>
            <span class="m-contact-item m-contact-item--phone">+91 9876543210</span>
        </div>
    </div>
</div>
{% endblock view_content %}

{% block addl_scripts %}
<script src="{% static 'js/home.js' %}"></script>
{% endblock addl_scripts %}